import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
      <meta name="google-site-verification" content="ANzkFFq3xUb9t9dIfRzQM-TorC9QIkS0bpxdi51Of2o" />
      <meta name="robots" content="index,follow" data-react-helmet="true" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, user-scalable=0, maximum-scale=1, minimum-scale=1"
      />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
